name: image_downloader_web
description: A Flutter plugin for downloading images from URL to user's device. This plugin only works for Flutter web.
version: 1.0.1
repository: https://github.com/hrvojecukman/image_downloader_web

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  universal_html: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

